version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hyperliquid
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    depends_on:
      - database
    volumes:
      - ./scripts:/app/scripts
      - ./config.json:/app/config.json
    command: ["cron", "-f", "/app/scripts/cronjobs"]
