version: '3'
services:
  hyperliquid-stats:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./app.py:/app/app.py
    ports:
      - 8001:8000
    environment:
      prometheus_multiproc_dir: /app
    networks:
      - hlstats

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hyperliquid
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - hlstats

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ./scripts:/app/scripts
      - ./config.json:/app/config.json
    command: ["cron", "-f", "/app/scripts/cronjobs"]
    networks:
    - hlstats
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - prometheus:/data
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/data/prom"
      - "--log.level=warn"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
      - "--web.listen-address=0.0.0.0:9090"
    networks:
    - hlstats

volumes:
  prometheus: {}

networks:
  hlstats: {}
